2023-02-17 12:11:15,075 INFO Bot: orderbot [@order_ltt_bot]
2023-02-17 12:11:15,220 WARNING Updates were skipped successfully.
2023-02-17 12:11:15,221 INFO Start polling.
2023-02-17 12:12:07,014 ERROR Task exception was never retrieved
future: <Task finished name='Task-36' coro=<Dispatcher._process_polling_updates() done, defined at /mnt/c/Users/LTT's PC/Desktop/restaraunt_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=TypeError("'coroutine' object is not subscriptable")>
Traceback (most recent call last):
  File "/mnt/c/Users/LTT's PC/Desktop/restaraunt_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/mnt/c/Users/LTT's PC/Desktop/restaraunt_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/mnt/c/Users/LTT's PC/Desktop/restaraunt_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/mnt/c/Users/LTT's PC/Desktop/restaraunt_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/mnt/c/Users/LTT's PC/Desktop/restaraunt_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/mnt/c/Users/LTT's PC/Desktop/restaraunt_bot/states/reg.py", line 40, in captcha
    key = await state.get_data()['key']
TypeError: 'coroutine' object is not subscriptable
